# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 17a19691218abaa1b66b2d9ae69d2050f3eaf122d0e83e48e21d9fd31f69b935f4ce8cd9efe354a843d656afa27c39ae53490191778ed578228e872a81c19bdb

test:
  secret_key_base: c4281cf9da32678ea176b8dfb45773f1fdac835bbabae5603850178975d8ee8aa474f65dad6e29384e3c4dba344feaee83d169fd47ad27b8b937fa1d6e5fb7b2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
